server:
  port: 8005


spring:
  application:
    name: tongmeng-service-pay #支付服务
  servlet:
    multipart:
      max-file-size: 1024MB # 默认1MB
      max-request-size: 1024MB
  cloud:
    nacos:
      config:
        server-addr: localhost:8848 # nacos 配置中心地址
      discovery:
        server-addr: 192.168.0.105:8848 # nacos 注册中心地址
        namespace: 5d485cb1-12bf-49a5-a881-35b812e1c5ea
management:
  endpoints:
    web:
      exposure:
        include=*: